apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: process-hello
  namespace: knative-samples
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.samples.hello.name
      source: dev.knative.samples/send-hello-source
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: process-hello