apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: catch-hello
  namespace: knative-samples
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.samples.hello.message
      source: dev.knative.samples/process-hello-source
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: catch-hello