apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-display
  namespace: knative-samples
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: event-display
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: helloworld-go
          # Source code: https://github.com/knative/eventing/tree/main/cmd/event_display
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display